steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: bash
    args:
      - '-c'
      - |
        git clone https://github.com/tejdev96/twocupsfull-demo-tejas.git /workspace/source
        cd /workspace/source
        git fetch origin ${_BRANCH}
        git checkout ${_BRANCH}
        git pull origin ${_BRANCH}
        changed_files=$(git diff-tree --no-commit-id --name-only -r ${_COMMIT_ID})
        echo "Changed files: $changed_files"
        if [ -z "$changed_files" ]; then
          echo "No changed files detected."
        else
          echo "Copying changed files..."
          for file in $changed_files; do
            dest_path="gs://${_GCS_BUCKET}/${_DEST_DIR}/${file}"
            echo "Copying $file to $dest_path"
            gsutil cp $file $dest_path
          done
        fi

substitutions:
  _BRANCH: dev
  _COMMIT_ID: ${COMMIT_SHA}
  _DEST_DIR: Tejas
  _GCS_BUCKET: test-bucket-1-one
  _REPO_DIR: /workspace/tejdev96/twocupsfull-demo-tejas
  _SOURCE_DIR: app

options:
  logging: CLOUD_LOGGING_ONLY
