steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/tejdev96/twocupsfull-demo-tejas.git']
  dir: /workspace
- name: 'gcr.io/cloud-builders/git'
  args: ['checkout', 'dev']
  dir: /workspace/twocupsfull-demo-tejas
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args:
  - '-c'
  - |
    echo "Defining source and destination directories..."
    SOURCE_DIR="app"
    DEST_DIR="Tejas"
    echo "Source directory: ${SOURCE_DIR}"
    echo "Destination directory: ${DEST_DIR}"
    echo "Listing contents of /workspace/twocupsfull-demo-tejas"
    ls /workspace/twocupsfull-demo-tejas
    echo "Listing contents of /workspace/twocupsfull-demo-tejas/${SOURCE_DIR}"
    ls /workspace/twocupsfull-demo-tejas/${SOURCE_DIR}
    echo "Copying from /workspace/twocupsfull-demo-tejas/${SOURCE_DIR} to gs://${_GCS_BUCKET}/${DEST_DIR}"
    gsutil cp -r /workspace/twocupsfull-demo-tejas/${SOURCE_DIR} gs://${_GCS_BUCKET}/${DEST_DIR}

options:
  logging: CLOUD_LOGGING_ONLY

